#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
write_files:
  - path: /root/docker-compose.yaml
    content: |
      version: "3.4"

      services:

        backend:
          image: leo45v/backend:v2
          depends_on:
            - pg-database
          environment:
            - DATA_SOURCE_URL=jdbc:postgresql://pg-database:5432/store
            - DATA_SOURCE_USERNAME=postgres
            - DATA_SOURCE_PASSWORD=Control123
            - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL81Dialect
          networks:
            - "net"
          ports:
            - 8080:8080

        pg-database:
          image: postgres:9.6-alpine
          restart: always
          volumes:
            - postgres-data:/var/lib/postgresql/data
          ports:
            - 5432:5432
          networks:
            - "net"
          environment:
            - POSTGRES_DB=store
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Control123

        front-pelis:
          image: leo45v/front-pelis:v2
          restart: always
          networks:
            - "net"

        nginx-proxy:
          image: leo45v/nginx-proxy:v1
          restart: always
          depends_on:
            - front-pelis
            - backend
          ports:
            - 80:80
            - 443:443
          networks:
            - "net"

      volumes:
        postgres-data:
          external: false

      networks:
        net:

runcmd:
  - docker-compose -f /root/docker-compose.yaml up -d